backend:
  name: github
  repo: donutpersonal-png/openworldschool
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "updates"
    label: "Updates"
    folder: "content/updates"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Language", name: "lang", widget: "select", options: ["en","ru"] }
      - { label: "Body", name: "body", widget: "markdown" }



